name = "SIMReconstruction"
uuid = "340e2c87-77e6-43c6-b8ac-bfdcf5517047"
authors = ["Martin Kunz <martinkunz@email.cz> and contributors"]
version = "1.0.0-DEV"

[compat]
Aqua = "0.7"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
